Feature 3
FaridaAdamuMagaji/module-1 pull request #1
Opened 2024-10-20 22:37 UTC by FaridaAdamuMagaji

made final changes "margins and paddings" to the web page

2024-10-22 10:09 UTC, Devsalmasaeed requested changes
Hi @FaridaAdamuMagaji ,

Good job so far!
You still need to work on some issues to get your project approved, but you are almost there!

<div style="text-align:center;">
    <img src="https://camo.githubusercontent.com/7cf1ba8db9cd08f454a9651e48128c064a4440a59881658c8593a41a8de243f3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f744b797263304e546c4563475764546870342f67697068792e676966" alt="Remote Collaboration" style="width:40%;">
</div>

### To Highlight 💯
- **Clean code** 👍
- **Good use of Gitflow** 👍
- **Implemented some project requirements** 👍

### Required Changes ♻️
- Please create different folder for your images
- Make sure to used professional PR title and description
- For best practice avoid using too much break in your code
- Make sure your code is well indented
- Used the same font-family,font-weight as used in figma
- Make sure your design is the same as the figma design the following is the area you should focus on

![Step 2 screenshot](https://images.tango.us/workflows/428637b2-956c-4000-80a3-360518664d99/steps/91396988-8244-4fc0-8822-6f945b7af213/ced23940-314b-4e1a-be58-6dbc16da853c.png?crop=focalpoint&fit=crop&w=1200&border=2%2CF4F2F7&border-radius=8%2C8%2C8%2C8&border-radius-inner=8%2C8%2C8%2C8&blend-align=bottom&blend-mode=normal&blend-x=0&blend-w=1200&blend64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmstdjIucG5n)

<br/>


![Step 1 screenshot](https://images.tango.us/workflows/9ec896c7-1f5f-4e4d-8a5a-962fcd5ea5aa/steps/0c378eeb-c262-4c0b-b8cc-769933dd9936/4dbe7e5d-a238-407b-9da4-1891fab0274b.png?crop=focalpoint&fit=crop&fp-x=0.4949&fp-y=0.5000&fp-z=1.0063&w=1200&border=2%2CF4F2F7&border-radius=8%2C8%2C8%2C8&border-radius-inner=8%2C8%2C8%2C8&blend-align=bottom&blend-mode=normal&blend-x=0&blend-w=1200&blend64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmstdjIucG5n&mark-x=399&mark-y=2&m64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL2JsYW5rLnBuZz9tYXNrPWNvcm5lcnMmYm9yZGVyPTYlMkNGRjc0NDImdz0zOTcmaD03ODcmZml0PWNyb3AmY29ybmVyLXJhZGl1cz0xMA%3D%3D)

<br/>

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

2024-10-22 10:09 UTC, Devsalmasaeed commented on index.html
> +            <br>
For best practice avoid using br in your code

2024-10-22 10:09 UTC, Devsalmasaeed commented on index.html
> +        <div class="location">
Avoid using too much br in your code

2024-10-22 10:09 UTC, Devsalmasaeed commented on index.html
> +    <br>
Make sure your code is well indented

2024-10-23 12:23 UTC, Devsalmasaeed requested changes
> Hi @FaridaAdamuMagaji ,
> 
> Good job so far! You still need to work on some issues to get your project approved, but you are almost there!
> 
> ![Remote Collaboration](https://camo.githubusercontent.com/7cf1ba8db9cd08f454a9651e48128c064a4440a59881658c8593a41a8de243f3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f744b797263304e546c4563475764546870342f67697068792e676966)
> ### To Highlight 💯
> * **Clean code** 👍
> * **Good use of Gitflow** 👍
> * **Implemented some project requirements** 👍
> 
> ### Required Changes ♻️
> * Make sure to used professional PR title and description
> * Make sure your design is the same as the figma design the following is the area you should focus on
> 
> ![Step 2 screenshot](https://camo.githubusercontent.com/b40e16d1ee0047d94847dfc5edec6411a4b06e41ab71a54d45d87a59d835af78/68747470733a2f2f696d616765732e74616e676f2e75732f776f726b666c6f77732f34323836333762322d393536632d343030302d383061332d3336303531383636346439392f73746570732f39313339363938382d383234342d346663302d383832322d3666393435623761663231332f63656432333934302d333134622d346531612d626535382d3664626331366461383533632e706e673f63726f703d666f63616c706f696e74266669743d63726f7026773d3132303026626f726465723d3225324346344632463726626f726465722d7261646975733d3825324338253243382532433826626f726465722d7261646975732d696e6e65723d3825324338253243382532433826626c656e642d616c69676e3d626f74746f6d26626c656e642d6d6f64653d6e6f726d616c26626c656e642d783d3026626c656e642d773d3132303026626c656e6436343d6148523063484d364c7939706257466e5a584d75644746755a32387564584d766333526864476c6a4c3231685a47557464326c30614331305957356e627931335958526c636d3168636d7374646a49756347356e)
> 
> 
> ![Step 1 screenshot](https://camo.githubusercontent.com/5193e95da28f0213cd65b18e4c6e72fd36da09938c60e4bac21848fcf10382f7/68747470733a2f2f696d616765732e74616e676f2e75732f776f726b666c6f77732f39656338393663372d316635662d346534642d386135612d3936326663643565613561612f73746570732f30633337386565622d633236322d346330622d623863632d3736393933336464393933362f34646265376535642d613233382d343037622d396461342d3138393166616230323734622e706e673f63726f703d666f63616c706f696e74266669743d63726f702666702d783d302e343934392666702d793d302e353030302666702d7a3d312e3030363326773d3132303026626f726465723d3225324346344632463726626f726465722d7261646975733d3825324338253243382532433826626f726465722d7261646975732d696e6e65723d3825324338253243382532433826626c656e642d616c69676e3d626f74746f6d26626c656e642d6d6f64653d6e6f726d616c26626c656e642d783d3026626c656e642d773d3132303026626c656e6436343d6148523063484d364c7939706257466e5a584d75644746755a32387564584d766333526864476c6a4c3231685a47557464326c30614331305957356e627931335958526c636d3168636d7374646a49756347356e266d61726b2d783d333939266d61726b2d793d32266d36343d6148523063484d364c7939706257466e5a584d75644746755a32387564584d766333526864476c6a4c324a73595735724c6e42755a7a397459584e7250574e76636d356c636e4d6d596d39795a4756795054596c4d6b4e47526a63304e44496d647a307a4f54636d614430334f44636d5a6d6c3050574e796233416d59323979626d56794c584a685a476c31637a30784d41253344253344)
> 
> 
> ### Optional Suggestions
> Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.
> 
> Cheers and Happy coding! 👏👏👏
> 
> _Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification._

2024-10-23 16:37 UTC, FaridaAdamuMagaji commented
Good day ma, i have already made changes to the two pictures above in my previous submission. @Devsalmasaeed 
![IMG_20241023_172007_732](https://github.com/user-attachments/assets/f1fb3f43-2244-40f6-aa65-8534c3b8618f)
![IMG_20241023_172105_747](https://github.com/user-attachments/assets/b19b9ff0-0683-4e5e-be4a-7bd618abb474)

2024-10-24 07:08 UTC, Devsalmasaeed commented
It's not reflecting on your website you met me @ Aisha Kwaku today 10am-3pm

On Wed, Oct 23, 2024, 5:38 PM Farida Adamu Magaji ***@***.***>
wrote:

> Good day ma, i have already made changes to the two pictures above in my
> previous submission. @Devsalmasaeed <https://github.com/Devsalmasaeed>
> IMG_20241023_172007_732.jpg (view on web)
> <https://github.com/user-attachments/assets/f1fb3f43-2244-40f6-aa65-8534c3b8618f>
> IMG_20241023_172105_747.jpg (view on web)
> <https://github.com/user-attachments/assets/b19b9ff0-0683-4e5e-be4a-7bd618abb474>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FaridaAdamuMagaji/module-1/pull/1#issuecomment-2432818231>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BIKQEEFERB3RWWQON23JJLDZ47GHZAVCNFSM6AAAAABQI53JQSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMZSHAYTQMRTGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-24 08:56 UTC, FaridaAdamuMagaji commented
ok @Devsalmasaeed

2024-11-15 15:36 UTC, Xfarouq commented
Hey @FaridaAdamuMagaji 
- make your video section i.e. the div which you put the video image and also the video image to all be 100% to avoid that white gap by the right of the website
- Also make sure all your images have title names for best practices
- Always make sure to name your images folder as assets not pictures for best practices
- Try to centrally align the second section please
Remember this is your last trial so try to rectify all corrections please

2024-11-20 06:52 UTC, Devsalmasaeed approved these changes
Hi @FaridaAdamuMagaji ,

Your project is complete! There is nothing else to say other than... it's time to merge it!!!
Congratulations! 🎉

<div style="text-align:center;">
    <img src="https://i.imgur.com/nvrw8p7.gif" alt="Remote Collaboration" style="width:100%;">
</div>

### Highlights
- ✅ **Professional Readme**
- ✅ **Good use of Gitflow**
- ✅ **UI looks like the Figma design**
- ✅ **Good use of HTML semantics**
- ✅ **Professional commit messages**
- ✅ **Professional PR title**
- ✅ **Professional PR description**

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

2024-11-25 12:40 UTC, merged